apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      containers:
        - name: video-api
          image: maestro:5000/video-api:latest
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DB_PORT
              value: "5432"
            - name: LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: video-api-env
            items:
              - key: .env
                path: .env
