# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: maestro:5000/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres:5432/auth_db"
          volumeMounts:
            - name: uploads-volume
              mountPath: /usr/src/app/uploads
            - name: detections-volume
              mountPath: /usr/src/app/detections
            - name: src-volume
              mountPath: /usr/src/app/src
      volumes:
        - name: uploads-volume
          hostPath:
            path: /mnt/data/uploads
        - name: detections-volume
          hostPath:
            path: /mnt/data/detections
        - name: src-volume
          hostPath:
            path: /mnt/data/src