apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-frontend
          image: maestro:5000/frontend:latest  # Asegúrate de usar la imagen correcta
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
