FROM postgres:latest

# Configura las variables de entorno directamente si quieres (opcional)
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=auth_db

# Expone el puerto 5432
EXPOSE 5432

